const subdatas = {
  trendingCollections: [
    {
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      name: "Brian",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ],
    },
    {
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      name: "Brian",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ],
    },
    {
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      name: "Brian",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ],
    },
    {
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      name: "Brian",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ],
    },
  ],
  endingSoon: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/lYJHuLrkZrCBoRyOviM8xuibyzyUU3GahfJaZv3rW6h4hIiAvWmeLtTwAqb8lxLk3GUAA1OSH_uRlmubUtd6SXdI-cMeptKnY6JrXg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 4,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/OWv7wjmQmfFB6-K4lj8Uux6lVhgP1NcPyykjeNR6OL_PPFibmwZ_qg6fO5oivpMlFYJOAXXID1prb11nPROLFkZezFAMVewUFpzesw=s265",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "Slabs",
      subtitle: "2017 PANINI PRIZM #191 LeBRON JAMES PSA 10 GEM MT",
      priceType: "wBNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/rUDaauhOwbb2FVfofPFi_dNPzM6ZKMZvHeYOId-EAIA8fHjXpg7P1lE_DM6Tn4FQ3WWxe7DstaIqZVx0svqITjPuioAJbaz2-s693DQ=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/q92sMO7GyqyPzBCUs8L1SjLqmo62IwcwkEXh1pgrFUyhvRrVpy-WHztoDPwjA-6pLtwzLA6cWvde2pAStNjgetyM-oNtGFIZDjuz=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  newlyMinted: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Ho9ZAiZK8t1pXaMfLbCYYKsD7EVYjhjxwNxHCMDbGqtJha7_rVp1J02gfzdQA64N7ySM8fVamEfck5FVz40JsHx8yMph3if0OWsWbg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/623b50317692c8d8743271ef88ef92ad.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/jreMqpfF4SW1XqghwVzHZq-7CPkHoasb_B_rhPofYcfw68C_Mk5ew1Zk8DNyL7BDzHGeyK3g2fztrJCsaJDm533OXEWKVfIu4wZZF-Y=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Q_zXSQvmfz1CuATXaxeg4RHAVjfaQVpdPIVfE_6BRycieILz7cvwnhdZ4zMtkq6uopi3IbsDACSq9v6qzhtzH5qUI0MU4wIUXDVVHw=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/af66f0027c38055eb01c866891ef0da0.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/sAxuWTRxdXMwZgFXD1gLSi8bkHGxKQ-jBPQJtzEaBZu7FjdFPWDj69c-IRNRCnSigS-u16T8a3RCrfWdEqmRah6IPok7zJesiWIz=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  onAuction: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RXZqp9wpTPALBf359G7Cn9ZEF6I7DhmX24xZEhjg5G3isFPkMm5Ms8a5b4SRDhxXTrDZEkJ6mPufiRQQ-IyCkLM=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/b47af109d011d8efb4fd2177f8120c9c.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RZtRK03-N6QTHEow3eUlJ8RGQp8XDx-CY1PP5rto41YI5FwmbvSRoJk2QZWNS5g_38Z2248SmTyAL3Q6YNf2FztjkBR9TggmHMHclS4=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RyZEBQoJ8jVne7hdV8J0Zkpn_W3tNsNPPyDlVLkpTsrXRXdB-azUa7jHbJZF36dvrsNNWDbqfWjhw9-zS2PcuSzi_L8zggTiBHEwcQ=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/s9k98zDtmQDkzD2dHR-IlS4-zmHUvjlwiqgZXwi5NByNexlOlrFlkscYjtOpIqD72b6ID9lphkZ8TpC1l5SXrL8Q_wmaXauzz5Gz4g=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "BNB",
      priceTitle: "Current Bid",
      price: "0.55 BNB",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
};
export const artistsData = [
  {
    id: 1,
    imagePath:
      "https://storage.opensea.io/files/fad8aac3dc77f370aa9f3fdcb970fc13.svg",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    fullname: "Dark Horse",
    address: "0xf64e9728ed212940c05c15939c2889a48b82a7f9",
    name: "@ixshells",
    description:
      "get art + exp music // a sense of rhythm fuels my research and real time visions become quests for parellels / Recen",
    followers: 1219,
    subdatas,
  },
  {
    id: 2,
    imagePath:
      "https://lh3.googleusercontent.com/j7GnRWvdlxYhthX0nZ5fkCIMpfcIhBjYIPlUC_6qBALLonTFmC7t2EptLG30fIDsddF79gEUpb0yC8bzvYUPiKF0n6kYmT9kKGmI6pQ=s265",
    avatarPath: "/assets/images/avatars/rabbit.gif",
    fullname: "Itzel Yard",
    address: "0xf64e9728ed212940c05c15939c2889a48b82a7f9",
    name: "@ixshells",
    description:
      "get art + exp music // a sense of rhythm fuels my research and real time visions become quests for parellels / Recen",
    followers: 1219,
    subdatas,
  },
  {
    id: 3,
    imagePath:
      "https://lh3.googleusercontent.com/bKWUtnrGlbZONIswkvi57zWXuOP_u5DuomyLg1K-EwASugfsgg8kVLSuW3DHZNzwsRfnj2iTUdEwcIIdfpXpwbR7XmOhiFXTMALPrA=s265",
    avatarPath: "/assets/images/avatars/giphy.gif",
    fullname: "Itzel Yard",
    address: "0xf64e9728ed212940c05c15939c2889a48b82a7f9",
    name: "@ixshells",
    description:
      "get art + exp music // a sense of rhythm fuels my research and real time visions become quests for parellels / Recen",
    followers: 1219,
    subdatas,
  },
  {
    id: 4,
    imagePath: "/assets/images/artist/trading.jpg",
    avatarPath: "/assets/images/avatars/rabbit.gif",
    fullname: "Itzel Yard",
    address: "0xf64e9728ed212940c05c15939c2889a48b82a7f9",
    name: "@ixshells",
    description:
      "get art + exp music // a sense of rhythm fuels my research and real time visions become quests for parellels / Recen",
    followers: 1219,
    subdatas,
  },
  {
    id: 5,
    imagePath:
      "https://storage.opensea.io/files/fad8aac3dc77f370aa9f3fdcb970fc13.svg",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    fullname: "Itzel Yard",
    address: "0xf64e9728ed212940c05c15939c2889a48b82a7f9",
    name: "@ixshells",
    description:
      "get art + exp music // a sense of rhythm fuels my research and real time visions become quests for parellels / Recen",
    followers: 1219,
    subdatas,
  },
  {
    id: 6,
    imagePath:
      "https://lh3.googleusercontent.com/j7GnRWvdlxYhthX0nZ5fkCIMpfcIhBjYIPlUC_6qBALLonTFmC7t2EptLG30fIDsddF79gEUpb0yC8bzvYUPiKF0n6kYmT9kKGmI6pQ=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    fullname: "Itzel Yard",
    address: "0xf64e9728ed212940c05c15939c2889a48b82a7f9",
    name: "@ixshells",
    description:
      "get art + exp music // a sense of rhythm fuels my research and real time visions become quests for parellels / Recen",
    followers: 1219,
    subdatas,
  },
  {
    id: 7,
    imagePath:
      "https://lh3.googleusercontent.com/bKWUtnrGlbZONIswkvi57zWXuOP_u5DuomyLg1K-EwASugfsgg8kVLSuW3DHZNzwsRfnj2iTUdEwcIIdfpXpwbR7XmOhiFXTMALPrA=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    fullname: "Itzel Yard",
    address: "0xf64e9728ed212940c05c15939c2889a48b82a7f9",
    name: "@ixshells",
    description:
      "get art + exp music // a sense of rhythm fuels my research and real time visions become quests for parellels / Recen",
    followers: 1219,
    subdatas,
  },
  {
    id: 8,
    imagePath:
      "https://lh3.googleusercontent.com/TSC82jUM6kC1DrgCJKJ42fuydmaSU117krcUJ-fm9HjQY9EWfc6eks6i6BD9I8jT4NsFhhi-f6Q2mrr4zQqrVhFoel9jR0HlImnC8Q=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    fullname: "Itzel Yard",
    address: "0xf64e9728ed212940c05c15939c2889a48b82a7f9",
    name: "@ixshells",
    description:
      "~ Calligraphy/pixel art crypto collectibles. Artist of Calligrafuturism ~ <br />NFT Lab - visual culture. Bathed in a neon-lit haze.",
    followers: 1219,
    subdatas,
  },
];
