export const auctionData = [
  {
    favourites: 5,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://storage.opensea.io/files/fad8aac3dc77f370aa9f3fdcb970fc13.svg",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "ZED RUN",
    subtitle: "Feel the thunder",
    priceType: "BNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 4,
    cardType: "video",
    videoPath:
      "https://storage.opensea.io/files/b160bf7e9e9c391b974b634808a65382.mp4",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/j7GnRWvdlxYhthX0nZ5fkCIMpfcIhBjYIPlUC_6qBALLonTFmC7t2EptLG30fIDsddF79gEUpb0yC8bzvYUPiKF0n6kYmT9kKGmI6pQ=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Podcasts",
    title: "DRL Historic Moments",
    subtitle: "Historic Moments: Racer3 Launch",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 19,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/bKWUtnrGlbZONIswkvi57zWXuOP_u5DuomyLg1K-EwASugfsgg8kVLSuW3DHZNzwsRfnj2iTUdEwcIIdfpXpwbR7XmOhiFXTMALPrA=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Radio",
    title: "Golden State Warriors Legacy Collection",
    subtitle: "Warriors 1956 Championship Ticket (3/10) ",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 8,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/TSC82jUM6kC1DrgCJKJ42fuydmaSU117krcUJ-fm9HjQY9EWfc6eks6i6BD9I8jT4NsFhhi-f6Q2mrr4zQqrVhFoel9jR0HlImnC8Q=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Politics",
    title: "Preakness x Zed Run NFT Collection",
    subtitle:
      "Special Edition: The Woodlawn Vase NFT & Physical Trophy (1-of-1)",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 2,
    cardType: "video",
    videoPath:
      "https://storage.opensea.io/files/b160bf7e9e9c391b974b634808a65382.mp4",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/geLbH887etJGZ-hssI0XCdROmAb3cr4rw0F8pJen8vg3y_nMxsMCdTizbgr7v0S3CFpTOrGyKCWc-ZmIIHnYu_5u5SY71T1c3yzKbQ=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Film",
    title: "Khabib Nurmagomedov NFT Gold Cards",
    subtitle: "Khabib NFT Gold Card [162/290]",
    priceType: "usdc",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 2,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://storage.opensea.io/files/1210bb2b85a405cbe3c71c2def45ee44.svg",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "ZED RUN",
    subtitle: "Messenger",
    priceType: "BNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 8,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/v2zNmHK2OnEXw_Pe2oFNjFYW4X_0-S-oHk4-sQ2YJD5etnUCDtrnfZImP3ZqB4UVZ03oZaKy0dgCeuRFLTQr0hsA4UUKnshljklgLw=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "Preakness x Zed Run NFT Collection",
    subtitle: "Special Edition: Triple Crown Winner Montage (1-of-1)",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 4,
    cardType: "audio",
    videoPath: "",
    audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
    imagePath:
      "https://lh3.googleusercontent.com/OWv7wjmQmfFB6-K4lj8Uux6lVhgP1NcPyykjeNR6OL_PPFibmwZ_qg6fO5oivpMlFYJOAXXID1prb11nPROLFkZezFAMVewUFpzesw=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "Slabs",
    subtitle: "2017 PANINI PRIZM #191 LeBRON JAMES PSA 10 GEM MT",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
];
export const reserveData = [
  {
    favourites: 5,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://storage.opensea.io/files/fad8aac3dc77f370aa9f3fdcb970fc13.svg",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "ZED RUN",
    subtitle: "Feel the thunder",
    priceType: "BNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 4,
    cardType: "video",
    videoPath:
      "https://storage.opensea.io/files/b160bf7e9e9c391b974b634808a65382.mp4",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/j7GnRWvdlxYhthX0nZ5fkCIMpfcIhBjYIPlUC_6qBALLonTFmC7t2EptLG30fIDsddF79gEUpb0yC8bzvYUPiKF0n6kYmT9kKGmI6pQ=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Podcasts",
    title: "DRL Historic Moments",
    subtitle: "Historic Moments: Racer3 Launch",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 19,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/bKWUtnrGlbZONIswkvi57zWXuOP_u5DuomyLg1K-EwASugfsgg8kVLSuW3DHZNzwsRfnj2iTUdEwcIIdfpXpwbR7XmOhiFXTMALPrA=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Radio",
    title: "Golden State Warriors Legacy Collection",
    subtitle: "Warriors 1956 Championship Ticket (3/10) ",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 8,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/TSC82jUM6kC1DrgCJKJ42fuydmaSU117krcUJ-fm9HjQY9EWfc6eks6i6BD9I8jT4NsFhhi-f6Q2mrr4zQqrVhFoel9jR0HlImnC8Q=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Politics",
    title: "Preakness x Zed Run NFT Collection",
    subtitle:
      "Special Edition: The Woodlawn Vase NFT & Physical Trophy (1-of-1)",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 2,
    cardType: "video",
    videoPath:
      "https://storage.opensea.io/files/b160bf7e9e9c391b974b634808a65382.mp4",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/geLbH887etJGZ-hssI0XCdROmAb3cr4rw0F8pJen8vg3y_nMxsMCdTizbgr7v0S3CFpTOrGyKCWc-ZmIIHnYu_5u5SY71T1c3yzKbQ=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Film",
    title: "Khabib Nurmagomedov NFT Gold Cards",
    subtitle: "Khabib NFT Gold Card [162/290]",
    priceType: "usdc",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 2,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://storage.opensea.io/files/1210bb2b85a405cbe3c71c2def45ee44.svg",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "ZED RUN",
    subtitle: "Messenger",
    priceType: "BNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 8,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/v2zNmHK2OnEXw_Pe2oFNjFYW4X_0-S-oHk4-sQ2YJD5etnUCDtrnfZImP3ZqB4UVZ03oZaKy0dgCeuRFLTQr0hsA4UUKnshljklgLw=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "Preakness x Zed Run NFT Collection",
    subtitle: "Special Edition: Triple Crown Winner Montage (1-of-1)",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 4,
    cardType: "audio",
    videoPath: "",
    audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
    imagePath:
      "https://lh3.googleusercontent.com/OWv7wjmQmfFB6-K4lj8Uux6lVhgP1NcPyykjeNR6OL_PPFibmwZ_qg6fO5oivpMlFYJOAXXID1prb11nPROLFkZezFAMVewUFpzesw=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "Slabs",
    subtitle: "2017 PANINI PRIZM #191 LeBRON JAMES PSA 10 GEM MT",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
];
export const soldData = [
  {
    favourites: 5,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://storage.opensea.io/files/fad8aac3dc77f370aa9f3fdcb970fc13.svg",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "ZED RUN",
    subtitle: "Feel the thunder",
    priceType: "BNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 4,
    cardType: "video",
    videoPath:
      "https://storage.opensea.io/files/b160bf7e9e9c391b974b634808a65382.mp4",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/j7GnRWvdlxYhthX0nZ5fkCIMpfcIhBjYIPlUC_6qBALLonTFmC7t2EptLG30fIDsddF79gEUpb0yC8bzvYUPiKF0n6kYmT9kKGmI6pQ=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Podcasts",
    title: "DRL Historic Moments",
    subtitle: "Historic Moments: Racer3 Launch",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 19,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/bKWUtnrGlbZONIswkvi57zWXuOP_u5DuomyLg1K-EwASugfsgg8kVLSuW3DHZNzwsRfnj2iTUdEwcIIdfpXpwbR7XmOhiFXTMALPrA=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Radio",
    title: "Golden State Warriors Legacy Collection",
    subtitle: "Warriors 1956 Championship Ticket (3/10) ",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 8,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/TSC82jUM6kC1DrgCJKJ42fuydmaSU117krcUJ-fm9HjQY9EWfc6eks6i6BD9I8jT4NsFhhi-f6Q2mrr4zQqrVhFoel9jR0HlImnC8Q=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Politics",
    title: "Preakness x Zed Run NFT Collection",
    subtitle:
      "Special Edition: The Woodlawn Vase NFT & Physical Trophy (1-of-1)",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 2,
    cardType: "video",
    videoPath:
      "https://storage.opensea.io/files/b160bf7e9e9c391b974b634808a65382.mp4",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/geLbH887etJGZ-hssI0XCdROmAb3cr4rw0F8pJen8vg3y_nMxsMCdTizbgr7v0S3CFpTOrGyKCWc-ZmIIHnYu_5u5SY71T1c3yzKbQ=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Film",
    title: "Khabib Nurmagomedov NFT Gold Cards",
    subtitle: "Khabib NFT Gold Card [162/290]",
    priceType: "usdc",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 2,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://storage.opensea.io/files/1210bb2b85a405cbe3c71c2def45ee44.svg",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "ZED RUN",
    subtitle: "Messenger",
    priceType: "BNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 8,
    cardType: "image",
    videoPath: "",
    audioPath: "",
    imagePath:
      "https://lh3.googleusercontent.com/v2zNmHK2OnEXw_Pe2oFNjFYW4X_0-S-oHk4-sQ2YJD5etnUCDtrnfZImP3ZqB4UVZ03oZaKy0dgCeuRFLTQr0hsA4UUKnshljklgLw=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "Preakness x Zed Run NFT Collection",
    subtitle: "Special Edition: Triple Crown Winner Montage (1-of-1)",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
  {
    favourites: 4,
    cardType: "audio",
    videoPath: "",
    audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
    imagePath:
      "https://lh3.googleusercontent.com/OWv7wjmQmfFB6-K4lj8Uux6lVhgP1NcPyykjeNR6OL_PPFibmwZ_qg6fO5oivpMlFYJOAXXID1prb11nPROLFkZezFAMVewUFpzesw=s265",
    avatarPath: "/assets/images/avatars/avatar.jpg",
    subCategory: "Sports",
    title: "Slabs",
    subtitle: "2017 PANINI PRIZM #191 LeBRON JAMES PSA 10 GEM MT",
    priceType: "wBNB",
    priceTitle: "Current Bid",
    price: "0.55 BNB",
    extraType: "none",
    daysLeft: 0,
    offerFor: 0,
    last: 0,
    endingIn: "Auction has ended",
  },
];