export const artData = {
  brandImage: "/assets/images/category/header.svg",
  title: "Discover Digital Art Collectibles",
  description:
    "Discover a world of beautiful works of art from the greatest digital artist in the Universe. BitCake premier’s digital masterpieces called NFT’s that contain distinct information that can be verified to claim authenticity. Secured on the Etherium blockchain, NFT art is a growing asset the world over.",
  trendingCollections: [
    {
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
      galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
      galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
      galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
      galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },
  ],
  endingSoon: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/lYJHuLrkZrCBoRyOviM8xuibyzyUU3GahfJaZv3rW6h4hIiAvWmeLtTwAqb8lxLk3GUAA1OSH_uRlmubUtd6SXdI-cMeptKnY6JrXg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/pTYAWUyuCtuM3Rq6E-73gpXItg9nxmVzSqDmSfWSuZNhNo9ogITnTBDR5Rc3Oy1IQKuhT08Iz3H7mmUTLIX--S6j9HrOz_jgx7dH=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/rUDaauhOwbb2FVfofPFi_dNPzM6ZKMZvHeYOId-EAIA8fHjXpg7P1lE_DM6Tn4FQ3WWxe7DstaIqZVx0svqITjPuioAJbaz2-s693DQ=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/_n97AXEcgAt_lqxAA6EF9HdL5Z812CaqIzAQmFjIDmBEBnBTruzuAl813UY5usNiyJIWiPQTaTkRRoq8u-jBTYb7ywwYaKQ7hytb=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  newlyMinted: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Ho9ZAiZK8t1pXaMfLbCYYKsD7EVYjhjxwNxHCMDbGqtJha7_rVp1J02gfzdQA64N7ySM8fVamEfck5FVz40JsHx8yMph3if0OWsWbg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/wn_PpbDoV6qRDmWmJCnHSMEaJpNxdRuJo5ebyEwuzCGKuHDtAfK1KC1bSM5y17hVUQoeKHMiCxAdAkbpQ5m0_YdfCoNQhnxCzxxhnw=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Q_zXSQvmfz1CuATXaxeg4RHAVjfaQVpdPIVfE_6BRycieILz7cvwnhdZ4zMtkq6uopi3IbsDACSq9v6qzhtzH5qUI0MU4wIUXDVVHw=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Z8c68EK7xpKXJ3uu4UAf0e6Nu2B5gdFHFxXn1EpEtvlM9Q7nljUlbzghfOr0ib9uLCxdG1O6xdSdhSnUCgaBQA4piOQpJ6YWJ3Qajg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  onAuction: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RXZqp9wpTPALBf359G7Cn9ZEF6I7DhmX24xZEhjg5G3isFPkMm5Ms8a5b4SRDhxXTrDZEkJ6mPufiRQQ-IyCkLM=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/UKVRbu53T-bqLKF6wpnkz2Knq0l2e8Q1Br6OH0ePLMJoEa5q20qlDj37JuAJeK0WtRRZE0YW1sI_XylmbKCkrvoDWWKfDeCZNphL1Ws=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RyZEBQoJ8jVne7hdV8J0Zkpn_W3tNsNPPyDlVLkpTsrXRXdB-azUa7jHbJZF36dvrsNNWDbqfWjhw9-zS2PcuSzi_L8zggTiBHEwcQ=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Z_2XZZASBISi0gwPeakTMOtFy2NFd654iGcHpu1tex3a93NBWzUdB25QILG6Qh_NEcfPBx8ocswX-0QT9Jyu-o99=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
};

export const audioData = {
  brandImage: "/assets/images/category/header.svg",
  title: "Discover Audio Collectibles",
  description:
    "Discover a world of music, podcasts, rare radio interviews and more direct from the celebrities, musicians, and personalities that create them. BitCake premier’s digital masterpieces called NFT’s that contain distinct information that can be verified to claim authenticity. Secured on the Etherium blockchain, NFT audio collectibles is a growing asset the world over.",
  trendingCollections: [
    {
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
      galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
      galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
      galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
      galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },
  ],
  endingSoon: [
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://storage.opensea.io/files/daa24e4214e39eaf63b19494f0dcad31.svg",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/q92sMO7GyqyPzBCUs8L1SjLqmo62IwcwkEXh1pgrFUyhvRrVpy-WHztoDPwjA-6pLtwzLA6cWvde2pAStNjgetyM-oNtGFIZDjuz=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://storage.opensea.io/files/f4d240b3ff1e8e41f50c6c8ba6a80b4e.svg",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/s9k98zDtmQDkzD2dHR-IlS4-zmHUvjlwiqgZXwi5NByNexlOlrFlkscYjtOpIqD72b6ID9lphkZ8TpC1l5SXrL8Q_wmaXauzz5Gz4g=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  newlyMinted: [
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/GCslVVOuxYAlHbke0TerYFo_wDriW9rRBwdxnKJyB9-SzSO2z6M8v4K4FF6hLJf3PZPS1s21nnECEawfmRKM0x1_swZKLoRFIs2kkL8=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/doRSEoys7Mw6k4-ovzOq8YVe_XiPKU5YUZ652eiHq6wtzcoL_T12trJnToxSSe_fwQUHDfDa4KunC72xWkfCqams3S47nasxOZ3xzZA=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://storage.opensea.io/files/fdd62b3f0460ce39518d94127b744f96.svg",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://storage.opensea.io/files/fa02d11a2f1b8fdaf76abefcb91c034c.svg",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  onAuction: [
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/q92sMO7GyqyPzBCUs8L1SjLqmo62IwcwkEXh1pgrFUyhvRrVpy-WHztoDPwjA-6pLtwzLA6cWvde2pAStNjgetyM-oNtGFIZDjuz=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/s9k98zDtmQDkzD2dHR-IlS4-zmHUvjlwiqgZXwi5NByNexlOlrFlkscYjtOpIqD72b6ID9lphkZ8TpC1l5SXrL8Q_wmaXauzz5Gz4g=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/3QaYIc51UKz527YNj2QFxnDW23FWid3opttUo_GHnVUcHQvsl5clKM8OysnL1Kk3VzGOSu600HVucR3xv8QQqmhFpcTdh2Fdqonp7w=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/-skCtHwslBWf37fH9_-Pl73TdzM1o7ChLMPFwOp1lVZHNUG016QNO7VJqGQXVad9M_s1YU0hpnseevSIWbqK8XDgCfSZ6EUYr7Tqrtk=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
};

export const videoData = {
  brandImage: "/assets/images/category/header.svg",
  title: "Discover Video Collectibles",
  description:
    "Discover a world of videos direct from the celebrities, musicians, and personalities that create them. BitCake premier’s digital masterpieces called NFT’s that contain distinct information that can be verified to claim authenticity. Secured on the Etherium blockchain, NFT video collectibles is a growing asset the world over.",
  trendingCollections: [
    {
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },
  ],
  endingSoon: [
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/623b50317692c8d8743271ef88ef92ad.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/jreMqpfF4SW1XqghwVzHZq-7CPkHoasb_B_rhPofYcfw68C_Mk5ew1Zk8DNyL7BDzHGeyK3g2fztrJCsaJDm533OXEWKVfIu4wZZF-Y=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/af66f0027c38055eb01c866891ef0da0.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/sAxuWTRxdXMwZgFXD1gLSi8bkHGxKQ-jBPQJtzEaBZu7FjdFPWDj69c-IRNRCnSigS-u16T8a3RCrfWdEqmRah6IPok7zJesiWIz=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/b47af109d011d8efb4fd2177f8120c9c.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RZtRK03-N6QTHEow3eUlJ8RGQp8XDx-CY1PP5rto41YI5FwmbvSRoJk2QZWNS5g_38Z2248SmTyAL3Q6YNf2FztjkBR9TggmHMHclS4=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/c95d234c8b12162f963246fdcfe3aa5d.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/4ArIcT-l2emLNfkIur8KGtSHjsA3DQGd5wlwyHUg2YhV-dUdhkfmZlUzi1otjTqELQqewNQPlOlyTRoc70AstB0EzAAwp0GcJKov0A=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  newlyMinted: [
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/623b50317692c8d8743271ef88ef92ad.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/jreMqpfF4SW1XqghwVzHZq-7CPkHoasb_B_rhPofYcfw68C_Mk5ew1Zk8DNyL7BDzHGeyK3g2fztrJCsaJDm533OXEWKVfIu4wZZF-Y=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/af66f0027c38055eb01c866891ef0da0.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/sAxuWTRxdXMwZgFXD1gLSi8bkHGxKQ-jBPQJtzEaBZu7FjdFPWDj69c-IRNRCnSigS-u16T8a3RCrfWdEqmRah6IPok7zJesiWIz=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/b47af109d011d8efb4fd2177f8120c9c.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RZtRK03-N6QTHEow3eUlJ8RGQp8XDx-CY1PP5rto41YI5FwmbvSRoJk2QZWNS5g_38Z2248SmTyAL3Q6YNf2FztjkBR9TggmHMHclS4=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/c95d234c8b12162f963246fdcfe3aa5d.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/4ArIcT-l2emLNfkIur8KGtSHjsA3DQGd5wlwyHUg2YhV-dUdhkfmZlUzi1otjTqELQqewNQPlOlyTRoc70AstB0EzAAwp0GcJKov0A=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  onAuction: [
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/623b50317692c8d8743271ef88ef92ad.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/jreMqpfF4SW1XqghwVzHZq-7CPkHoasb_B_rhPofYcfw68C_Mk5ew1Zk8DNyL7BDzHGeyK3g2fztrJCsaJDm533OXEWKVfIu4wZZF-Y=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/af66f0027c38055eb01c866891ef0da0.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/sAxuWTRxdXMwZgFXD1gLSi8bkHGxKQ-jBPQJtzEaBZu7FjdFPWDj69c-IRNRCnSigS-u16T8a3RCrfWdEqmRah6IPok7zJesiWIz=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/b47af109d011d8efb4fd2177f8120c9c.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RZtRK03-N6QTHEow3eUlJ8RGQp8XDx-CY1PP5rto41YI5FwmbvSRoJk2QZWNS5g_38Z2248SmTyAL3Q6YNf2FztjkBR9TggmHMHclS4=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/c95d234c8b12162f963246fdcfe3aa5d.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/4ArIcT-l2emLNfkIur8KGtSHjsA3DQGd5wlwyHUg2YhV-dUdhkfmZlUzi1otjTqELQqewNQPlOlyTRoc70AstB0EzAAwp0GcJKov0A=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
};

export const collectibleData = {
  brandImage: "/assets/images/category/header.svg",
  title: "Explore Collectibles",
  description:
    "The way we value internet-native items is changing with the development of blockchain technology. Kittens, punks, and memes are now trading digital wallets for cryptocurrencies, and the online collectibles market is taking shape before our eyes.<br /><br />Scarce digital property is cropping up in all kinds of industries around the world, and OpenSea is on a mission to house internet goods from all corners of the ecosystem. Own, buy, and sell rare and exclusive NFTs from CryptoKitties, Axie Infinity, and beyond.",
  trendingCollections: [
    {
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },
  ],
  endingSoon: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/o5FcMN0-PJfYcgknIPb5B4QVl7AJu0kG8GA9Z9McysgnEof7Naxv7zZLemTJQg3PWWNcLaWzMrv2NJ22hQRoPt7VAQCiFv_WnSPV=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/5QGg82ffZPNoYFTIvOolucR9YYLKzGFxnb0hp7uUdQcHGL0Sq_ARvUZ4N3ce2w2zWOz3sh-ZeNgFbwydr29W18HML7-errVxI7R7=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/ReAGBoPI0DKV77f6W1uUzMtH7gF84uE-Mie6XwmV_w8ONzj7R8H_ORj_gh9QbsT0a0TRTBTvHr9ObYQNLmO1IWCn5yAGv-SSdm5hHw=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/0Z28-lO4Urk6owPoxEjkVh1CCkoFQyScJFB-0p5BMZMMG6uBTZlFnjpY16Zg1KY159KL1cNfkmMYOp4pR_xXHFHVnniioYi0qNfXv3I=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  newlyMinted: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Ho9ZAiZK8t1pXaMfLbCYYKsD7EVYjhjxwNxHCMDbGqtJha7_rVp1J02gfzdQA64N7ySM8fVamEfck5FVz40JsHx8yMph3if0OWsWbg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/wn_PpbDoV6qRDmWmJCnHSMEaJpNxdRuJo5ebyEwuzCGKuHDtAfK1KC1bSM5y17hVUQoeKHMiCxAdAkbpQ5m0_YdfCoNQhnxCzxxhnw=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Q_zXSQvmfz1CuATXaxeg4RHAVjfaQVpdPIVfE_6BRycieILz7cvwnhdZ4zMtkq6uopi3IbsDACSq9v6qzhtzH5qUI0MU4wIUXDVVHw=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Z8c68EK7xpKXJ3uu4UAf0e6Nu2B5gdFHFxXn1EpEtvlM9Q7nljUlbzghfOr0ib9uLCxdG1O6xdSdhSnUCgaBQA4piOQpJ6YWJ3Qajg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  onAuction: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RXZqp9wpTPALBf359G7Cn9ZEF6I7DhmX24xZEhjg5G3isFPkMm5Ms8a5b4SRDhxXTrDZEkJ6mPufiRQQ-IyCkLM=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/UKVRbu53T-bqLKF6wpnkz2Knq0l2e8Q1Br6OH0ePLMJoEa5q20qlDj37JuAJeK0WtRRZE0YW1sI_XylmbKCkrvoDWWKfDeCZNphL1Ws=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RyZEBQoJ8jVne7hdV8J0Zkpn_W3tNsNPPyDlVLkpTsrXRXdB-azUa7jHbJZF36dvrsNNWDbqfWjhw9-zS2PcuSzi_L8zggTiBHEwcQ=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Z_2XZZASBISi0gwPeakTMOtFy2NFd654iGcHpu1tex3a93NBWzUdB25QILG6Qh_NEcfPBx8ocswX-0QT9Jyu-o99=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
};

export const sportData = {
  brandImage: "/assets/images/category/header.svg",
  title: "Discover Sports Collectibles",
  description:
    "Discover a world of sports collectibles direct from the official franchises, athletes, and digital artists. BitCake premier’s digital masterpieces called NFT’s that contain distinct information that can be verified to claim authenticity. Secured on the Etherium blockchain, NFT sports collectibles is a growing asset the world over.",
  trendingCollections: [
    {
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },{
      avatarPath: "/assets/images/avatars/avatar.jpg",
      name: "Brian",
galleryName: "Guns N' Roses Collectibles",
      images: [
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/featured-images/unstoppable-domains-featured.png",
        "https://storage.googleapis.com/opensea-static/official-ens-logo.png",
        "https://storage.googleapis.com/opensea-static/featured-images/decentraland-featured.png",
      ]
    },
  ],
  endingSoon: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/lYJHuLrkZrCBoRyOviM8xuibyzyUU3GahfJaZv3rW6h4hIiAvWmeLtTwAqb8lxLk3GUAA1OSH_uRlmubUtd6SXdI-cMeptKnY6JrXg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/pTYAWUyuCtuM3Rq6E-73gpXItg9nxmVzSqDmSfWSuZNhNo9ogITnTBDR5Rc3Oy1IQKuhT08Iz3H7mmUTLIX--S6j9HrOz_jgx7dH=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/rUDaauhOwbb2FVfofPFi_dNPzM6ZKMZvHeYOId-EAIA8fHjXpg7P1lE_DM6Tn4FQ3WWxe7DstaIqZVx0svqITjPuioAJbaz2-s693DQ=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/_n97AXEcgAt_lqxAA6EF9HdL5Z812CaqIzAQmFjIDmBEBnBTruzuAl813UY5usNiyJIWiPQTaTkRRoq8u-jBTYb7ywwYaKQ7hytb=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  newlyMinted: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Ho9ZAiZK8t1pXaMfLbCYYKsD7EVYjhjxwNxHCMDbGqtJha7_rVp1J02gfzdQA64N7ySM8fVamEfck5FVz40JsHx8yMph3if0OWsWbg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/wn_PpbDoV6qRDmWmJCnHSMEaJpNxdRuJo5ebyEwuzCGKuHDtAfK1KC1bSM5y17hVUQoeKHMiCxAdAkbpQ5m0_YdfCoNQhnxCzxxhnw=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Q_zXSQvmfz1CuATXaxeg4RHAVjfaQVpdPIVfE_6BRycieILz7cvwnhdZ4zMtkq6uopi3IbsDACSq9v6qzhtzH5qUI0MU4wIUXDVVHw=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Z8c68EK7xpKXJ3uu4UAf0e6Nu2B5gdFHFxXn1EpEtvlM9Q7nljUlbzghfOr0ib9uLCxdG1O6xdSdhSnUCgaBQA4piOQpJ6YWJ3Qajg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  onAuction: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RXZqp9wpTPALBf359G7Cn9ZEF6I7DhmX24xZEhjg5G3isFPkMm5Ms8a5b4SRDhxXTrDZEkJ6mPufiRQQ-IyCkLM=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/UKVRbu53T-bqLKF6wpnkz2Knq0l2e8Q1Br6OH0ePLMJoEa5q20qlDj37JuAJeK0WtRRZE0YW1sI_XylmbKCkrvoDWWKfDeCZNphL1Ws=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RyZEBQoJ8jVne7hdV8J0Zkpn_W3tNsNPPyDlVLkpTsrXRXdB-azUa7jHbJZF36dvrsNNWDbqfWjhw9-zS2PcuSzi_L8zggTiBHEwcQ=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Z_2XZZASBISi0gwPeakTMOtFy2NFd654iGcHpu1tex3a93NBWzUdB25QILG6Qh_NEcfPBx8ocswX-0QT9Jyu-o99=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
subCategory: "Sports",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
};
