export const galleryData = {
  avatarImage: "/assets/images/avatars/avatar.jpg",
  brandImage: "/assets/images/category/header.svg",
  title: "Guns N' Roses",
  description:
    "Pulsquares is an experimental generative math art NFT project. It aims to explore some boundaries of NFTs mechanisms through empirical practice. It's deflationary, free, and incorporates two main mechanisms: burn-to-compose and the Gallery system.<br /><br /> <b>To know more visit:</b><br />Website: <a href='https://pulsquares.art' class='text-blue-500'>https://pulsquares.art</a><br />Discord: <a href='https://discord.gg/4yAFVJbxnm' class='text-blue-500'>https://discord.gg/4yAFVJbxnm</a>",
  endingSoon: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/lYJHuLrkZrCBoRyOviM8xuibyzyUU3GahfJaZv3rW6h4hIiAvWmeLtTwAqb8lxLk3GUAA1OSH_uRlmubUtd6SXdI-cMeptKnY6JrXg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://storage.opensea.io/files/daa24e4214e39eaf63b19494f0dcad31.svg",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/rUDaauhOwbb2FVfofPFi_dNPzM6ZKMZvHeYOId-EAIA8fHjXpg7P1lE_DM6Tn4FQ3WWxe7DstaIqZVx0svqITjPuioAJbaz2-s693DQ=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/q92sMO7GyqyPzBCUs8L1SjLqmo62IwcwkEXh1pgrFUyhvRrVpy-WHztoDPwjA-6pLtwzLA6cWvde2pAStNjgetyM-oNtGFIZDjuz=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  newlyMinted: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Ho9ZAiZK8t1pXaMfLbCYYKsD7EVYjhjxwNxHCMDbGqtJha7_rVp1J02gfzdQA64N7ySM8fVamEfck5FVz40JsHx8yMph3if0OWsWbg=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/623b50317692c8d8743271ef88ef92ad.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/jreMqpfF4SW1XqghwVzHZq-7CPkHoasb_B_rhPofYcfw68C_Mk5ew1Zk8DNyL7BDzHGeyK3g2fztrJCsaJDm533OXEWKVfIu4wZZF-Y=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/Q_zXSQvmfz1CuATXaxeg4RHAVjfaQVpdPIVfE_6BRycieILz7cvwnhdZ4zMtkq6uopi3IbsDACSq9v6qzhtzH5qUI0MU4wIUXDVVHw=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/af66f0027c38055eb01c866891ef0da0.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/sAxuWTRxdXMwZgFXD1gLSi8bkHGxKQ-jBPQJtzEaBZu7FjdFPWDj69c-IRNRCnSigS-u16T8a3RCrfWdEqmRah6IPok7zJesiWIz=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
  onAuction: [
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RXZqp9wpTPALBf359G7Cn9ZEF6I7DhmX24xZEhjg5G3isFPkMm5Ms8a5b4SRDhxXTrDZEkJ6mPufiRQQ-IyCkLM=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "video",
      videoPath:
        "https://storage.opensea.io/files/b47af109d011d8efb4fd2177f8120c9c.mp4",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RZtRK03-N6QTHEow3eUlJ8RGQp8XDx-CY1PP5rto41YI5FwmbvSRoJk2QZWNS5g_38Z2248SmTyAL3Q6YNf2FztjkBR9TggmHMHclS4=s317",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "image",
      videoPath: "",
      audioPath: "",
      imagePath:
        "https://lh3.googleusercontent.com/RyZEBQoJ8jVne7hdV8J0Zkpn_W3tNsNPPyDlVLkpTsrXRXdB-azUa7jHbJZF36dvrsNNWDbqfWjhw9-zS2PcuSzi_L8zggTiBHEwcQ=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
    {
      favourites: 5,
      cardType: "audio",
      videoPath: "",
      audioPath: "https://www.mfiles.co.uk/mp3-downloads/gs-cd-track2.mp3",
      imagePath:
        "https://lh3.googleusercontent.com/s9k98zDtmQDkzD2dHR-IlS4-zmHUvjlwiqgZXwi5NByNexlOlrFlkscYjtOpIqD72b6ID9lphkZ8TpC1l5SXrL8Q_wmaXauzz5Gz4g=s302",
      avatarPath: "/assets/images/avatars/avatar.jpg",
      title: "ZED RUN",
      subtitle: "Feel the thunder",
      priceType: "eth",
      priceTitle: "Current Bid",
      price: "0.55 ETH",
      extraType: "none",
      daysLeft: 0,
      offerFor: 0,
      last: 0,
      endingIn: "Auction has ended",
    },
  ],
};